apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: gradle-build-run-
spec:
  serviceAccountName: ''
  pipelineRef:
    name: gradle-build
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-credentials
    secret:
      secretName: git-credentials
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  params:
  - name: repo-url
    value: https://github.com/squidmin/java11-spring-gradle-bigquery-reference
  - name: image-reference
    value: us-central1-docker.pkg.dev/lofty-root-378503/java11-spring-gradle-bigquery-reference:latest
