apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: gradle-build-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: gradle-build
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-credentials
    secret:
      secretName: git-credentials
  params:
  - name: repo-url
    value: https://github.com/squidmin/java11-spring-gradle-cucumber-reference
  - name: image-reference
    value: container.registry.com/sublocation/java11-spring-gradle-cucumber-reference:latest
