apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle-build
spec:
  description: Gradle build
  workspaces:
  - name: source
  steps:
  - name: dump-directory
    image: alpine
    command:
      - /bin/sh
    args:
      - '-c'
      - |
        set -ex
        find /workspace
  - name: gradle-build
    image: alpine:latest
    script: |
      #!/bin/sh
      ls -la
