apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle-build-test
spec:
  description: Gradle build
  workspaces:
  - name: source
  steps:
  - name: dump-directory
    image: alpine
    command:
      - /bin/sh
    args:
      - '-c'
      - |
        set -ex
        find /workspace
  - name: build
    image: alpine:latest
    script: |
      #!/usr/bin/env sh
      cd $(workspaces.source.path) && ls -la
